### PR TITLE
Check for success/failure on websocket handshake completion (fixes #452)

### LINKED ISSUE #452: WebSocket client fails silently on handshake failure
The issue is that `WebSocketClient.HandshakeOperator` does not check for failure on handshake completion.

The following code reproduces the issue:

``` java
final RxServer<HttpServerRequest<ByteBuf>, HttpServerResponse<ByteBuf>> server = RxNetty.createHttpServer(0, new RequestHandler<ByteBuf, ByteBuf>() {
    @Override
    public Observable<Void> handle(HttpServerRequest<ByteBuf> request, HttpServerResponse<ByteBuf> response) {
        response.setStatus(HttpResponseStatus.BAD_REQUEST);
        return Observable.empty();
    }
});
server.start();

final LinkedBlockingQueue<Notification<Throwable>> q = new LinkedBlockingQueue<Notification<Throwable>>();
RxNetty.newWebSocketClientBuilder("localhost", server.getServerPort())
        .withWebSocketVersion(WebSocketVersion.V13)
        .enableWireLogging(LogLevel.ERROR)
        .build()
        .connect()
        .timeout(3, java.util.concurrent.TimeUnit.SECONDS)
        .subscribe(new Subscriber<ObservableConnection<WebSocketFrame, WebSocketFrame>>() {
            private void put(Notification<? extends Throwable> notif) {
                try {
                    q.put((Notification<Throwable>) notif);
                } catch(InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }
            public void onNext(ObservableConnection<WebSocketFrame, WebSocketFrame> con) {
                put(Notification.createOnNext(new IllegalStateException("Connection should not have succeeded")));
            }
            public void onCompleted() {
                put(Notification.<Throwable>createOnCompleted());
            }
            public void onError(Throwable cause) {
                put(Notification.createOnNext(cause));
            }
        });
final Notification<Throwable> n = q.poll(5, TimeUnit.SECONDS);
assert n != null;
assert n.isOnNext();
assert n.getValue() instanceof WebSocketHandshakeException;
server.shutdown();
```

Changing the handshake listener (in `WebSocketClient.HandshakeOperator`) to the following resolves the issue:

``` java
handler.addHandshakeFinishedListener(new ChannelFutureListener() {
    @Override
    public void operationComplete(ChannelFuture future) throws Exception {
        if (future.isCancelled()) {
            originalSubscriber.unsubscribe(); // should this be unsubscribe, or onCompleted?
        } else if (future.isSuccess()) {
            originalSubscriber.onNext(connection);
            originalSubscriber.onCompleted();
        } else {
            originalSubscriber.onError(future.cause());
        }
    }
});
```

### PR DESCRIPTION
**Pull request by edwinchoi**
This fixes the issue where the WebSocket client fails to signal error on handshake failure.

### CODE REVIEW

File: rxnetty/src/main/java/io/reactivex/netty/protocol/http/websocket/WebSocketClient.java [hunk 1]
```diff
@@ -80,8 +80,14 @@ public void onNext(final ObservableConnection<T, T> connection) {
                         handler.addHandshakeFinishedListener(new ChannelFutureListener() {
                             @Override
                             public void operationComplete(ChannelFuture future) throws Exception {
-                                originalSubscriber.onNext(connection);
-                                originalSubscriber.onCompleted();
+                                if (future.isCancelled()) {
+                                    originalSubscriber.unsubscribe();
```
Comment (NiteshKant) [inline rxnetty/src/main/java/io/reactivex/netty/protocol/http/websocket/WebSocketClient.java]: The below code is sufficient for handling the future completion:

``` java
if (future.isSuccess()) {
       originalSubscriber.onNext(connection);
       originalSubscriber.onCompleted();
} else {
        originalSubscriber.onError(future.cause());
}
```

For cancellation, `isSuccess()` returns `false` and `cause()` returns `CancellationException`

**Comment by NiteshKant** [comment]
Thanks @edwinchoi for the PR, apart from the minor comment it looks :+1:

**Comment by edwinchoi** [comment]
@NiteshKant incorporated the change. Thanks.
